Artur Wodarz - Solution
CodingDojoSilesia/startrek-kata pull request #1
Opened 2019-11-05 00:37 UTC by Bornegio

2019-11-05 19:54 UTC, firemark requested changes

2019-11-05 19:54 UTC, firemark commented on test/galaxy.test.js
> +        result.forEach(el => {
much cleaner would be to make a count function:

```js
function count(type) {
  return result.filter(o => o.type === type).length;
}
expect(count('ship')).toBe(config.FOO);

```

2019-11-05 19:54 UTC, firemark commented on test/game.test.js
> +            [ks[0][0], ks[0][1], ks[0][2], us, us, us, us, us],
nice :)

2019-11-05 19:54 UTC, firemark commented on test/renderer.test.js
> +    it("Should display quadrant of given schema", () => {
amazing!

2019-11-05 20:10 UTC, Bornegio commented on src/core/galaxy.js
> +            if(so.quadrant.x == quadrant.x && so.quadrant.y == quadrant.y){
Actually mathSupport module has hasSamePos() method, which compares two instances of point. Can be used with both quadrants and sectors. I just missed this line when I was refactoring code. Gonna change that. Thanks

2019-11-07 17:14 UTC, imatw4r reviewed
Your code looks pretty clean, I really like it! 
Even the variable names are pretty good!
Keep up the good work!

2019-11-07 17:14 UTC, imatw4r commented on src/core/game.js
> +        if(power >= this.player.power){
Self destruction with `power > this.player.power` would be interesting option for a tie result.

2019-11-07 17:14 UTC, imatw4r commented on src/core/game.js
> +            console.log('There is no remaining klingons in your current quadrant');
I would add `return` statement here and get rid of `else` statement below. I like the approach with sticking to the rule: quick ASAP. Basically return from the function as fast as you can. If you can.

2019-11-07 17:14 UTC, imatw4r commented on src/core/game.js
> +            if (hasHit){
Same here. You could do
```
if (!hasHit) {
    console.log("You missed!")
    return
}

closestKlingons[0].reducePower(power);
<rest of the code>
```
It definitely decreases the nesting levels and removes some IFs

2019-11-07 17:14 UTC, imatw4r commented on src/core/game.js
> +                this.galaxy.getSurrouningSectors(so.sector).forEach(p => {
Typo `getSurrouningSectors` => `getSurroundingSectors`

2019-11-07 17:14 UTC, imatw4r commented on src/index.js
> +    game.checkIfOver();
Is it necessary to keep it here? Shouldn't it be at the end of the loop? I would expect the end game check after each move not before it.

2022-04-07 08:43 UTC, closed without merging